# Generated by Django 3.2.9 on 2022-03-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, verbose_name='Item Name')),
                ('car_make', models.CharField(max_length=30, verbose_name='Car Make')),
                ('model_number', models.CharField(max_length=30, verbose_name='Model Number')),
                ('price', models.FloatField(max_length=30, verbose_name='Item Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
    ]
